paths:
  ibtracs: data/IBTrACS/ibtracs.since1980.list.v04r00.csv
  ibtracs_preprocessed: data/IBTrACS/ibtracs_preprocessed.csv
  era5: /scratch/cdauvill/era5/pangu/
  era5_patches: /scratch/cdauvill/era5/storm_patches/5/
  hursat_b1: /scratch/cdauvill/hursat-b1/
  hursat_b1_preprocessed: /scratch/cdauvill/hursat-b1-preprocessed/
  hursat_b1_cache: /scratch/cdauvill/hursat-b1-preprocessed/cache.nc
  tcir: /home/cdauvill/scratch/tcir/TCIR-ATLN_EPAC_WPAC.h5
  tcir_info_preprocessed: /home/cdauvill/scratch/tcir/tcir_info_preprocessed.csv
  tcir_datacube_preprocessed: /home/cdauvill/scratch/tcir/tcir_datacube_preprocessed.csv
  checkpoints: /home/cdauvill/scratch/checkpoints/

tcir:
  # Fraction of the tcir dataset to use (use less data for debugging)
  subsample: true  # true / false
  subsample_fraction: 0.2

era5:
  # Variables to include in the reanalysis data
  atmo_variables: ['u', 'v']
  surface_variables: ['u10', 'v10', 'msl', 't2m']
  # Atmospheric pressure levels to include
  pressure_levels: [200, 500, 850]
