paths:
  ibtracs: data/IBTrACS/ibtracs.since1980.list.v04r00.csv
  ibtracs_preprocessed: data/IBTrACS/ibtracs_preprocessed.csv
  era5: /scratch/cdauvill/era5/pangu/
  era5_patches: /scratch/cdauvill/era5/storm_patches/5/
  hursat_b1: /scratch/cdauvill/hursat-b1/
  hursat_b1_preprocessed: /scratch/cdauvill/hursat-b1-preprocessed/
  hursat_b1_cache: /scratch/cdauvill/hursat-b1-preprocessed/cache.nc
  tcir: /home/cdauvill/scratch/cdauvill/tcir/TCIR-ATLN_EPAC_WPAC.h5
  tcir_preprocessed_dir: /home/cdauvill/scratch/cdauvill/tcir/preprocessed_small
  checkpoints: /home/cdauvill/scratch/checkpoints/

preprocessing:
  # Number of cross-validation folds to create
  n_folds: 5
  # Which steps will be included either for the contextual variables
  # or the target.
  # For examples, [-1., 0, 1.] means for every sample, the variables
  # (either contextual or targets) will be included for time steps
  # t-1, t, and t+1.
  steps: [-3, -2, -1, 0, 1, 2, 3, 4]
  # Fraction of the tcir dataset to use (use less data for debugging)
  subsample: false  # true / false
  subsample_fraction: 0.05
  # Minimum SSHS category to include
  min_category: -1.

era5:
  # Variables to include in the reanalysis data
  atmo_variables: ['u', 'v']
  surface_variables: ['u10', 'v10', 'msl', 't2m']
  # Atmospheric pressure levels to include
  pressure_levels: [200, 500, 850]
