experiment:
  name: st_norm_rotate&crop
  # Number of past time steps given as input
  past_steps: 4
  # Number of time steps to predict at once
  future_steps: 4
tasks:
  # Parameters specific to each task
  # Output distribution:
  # - "deterministic" (MSE loss)
  # - "normal"
  # - "qc" (quantiles composite)
  intensity:
    output_variables: ['INTENSITY']
    distribution: normal 
  # location:
    # output_variables: ['LAT', 'LON']
    # distribution: deterministic
training_settings:
  epochs: 100
  batch_size: 128
  # Trainer precision, usually "bf16-mixed" or "32-true"
  precision: 32-true
model_hyperparameters:
  # Number of convolutional blocks (Each block has 2 Conv layers)
  encoder_depth: 4
  # Number of channels in the first hidden layer
  encoder_channels: 4
  # Weight decay
  weight_decay: 0

