experiment:
  name: e5_CQR
  # Output distribution:
  # - "deterministic" (MSE regression)
  # - "normal" (Normal distribution)
  # - "qc" (quantiles composite)
  distribution: qc 
  # Type of input data. Can be "era5", "hursat" or "era5+hursat"
  input_data: era5
  # Number of past time steps given as input
  past_steps: 4
  # Number of time steps to predict at once
  future_steps: 4
training_settings:
  epochs: 100
  batch_size: 128
  # Trainer precision, usually "bf16-mixed"
  precision: bf16-mixed 
model_hyperparameters:
  # Number of convolutional blocks (Each block has 2 Conv layers)
  depth: 5
  # Number of channels in the first hidden layer
  hidden_channels: 4


