experiment:
  name: vmax_all_optim
  # Number of past time steps given as input
  past_steps: 4
  # Number of time steps to predict at once
  future_steps: 4
  # Size of the input and output patches, in pixels (resolution=0.07°)
  patch_size: 128
tasks:
  # Parameters specific to each task
  # Output distribution:
  # - "deterministic" (MSE loss)
  # - "normal"
  # - "qc" (quantiles composite)
  vmax:
    output_variables: ['INTENSITY']
    distribution: deterministic
  mslp:
    output_variables: ['MSLP']
    distribution: deterministic
  r34_avg:
    output_variables: ['R35_4qAVG']
    distribution: deterministic
  location:
    output_variables: ['LAT', 'LON']
    distribution: deterministic
training_settings:
  epochs: 100
  batch_size: 128
  # Trainer precision, usually "bf16-mixed" or "32-true"
  precision: 32-true
  # Learning-related params
  initial_lr: 0.001
  # Weight decay
  weight_decay: 0
model_hyperparameters:
  # What type of base block to use (either 'cbam' or 'conv')
  base_block: conv
  # Number of convolutional blocks (Each block has 2 Conv layers)
  encoder_depth: 7
  # Number of channels in the first hidden layer
  encoder_channels: 2
  # Reduction factor in the Common Linear Module
  clm_reduction_factor: 4

